# config.yaml

# URLs and File Paths
target_url: "https://fbs.intranet.smu.edu.sg/home"
credentials_filepath: "credentials.json"
screenshot_filepath: "./screenshot_log/"
booking_log_filepath: "./booking_log/"

# Scraping Parameters
date_raw: "1 November 2024"
duration_hours: 2.5
start_time: "11:00"

# Filters
building_names:
  - "School of Accountancy"
  - "School of Computing & Information Systems 1"

floors:
  - "Basement 1"
  - "Level 1"
  - "Level 2"
  - "Level 4"

facility_types:
  - "Meeting Pod"
  - "Group Study Room"

equipment:
  - # List equipment if any, e.g., "Projector"

# Valid Constants
valid_time:
  - "00:00"
  - "00:30"
  - "01:00"
  - "01:30"
  - "02:00"
  - "02:30"
  - "03:00"
  - "03:30"
  - "04:00"
  - "04:30"
  - "05:00"
  - "05:30"
  - "06:00"
  - "06:30"
  - "07:00"
  - "07:30"
  - "08:00"
  - "08:30"
  - "09:00"
  - "09:30"
  - "10:00"
  - "10:30"
  - "11:00"
  - "11:30"
  - "12:00"
  - "12:30"
  - "13:00"
  - "13:30"
  - "14:00"
  - "14:30"
  - "15:00"
  - "15:30"
  - "16:00"
  - "16:30"
  - "17:00"
  - "17:30"
  - "18:00"
  - "18:30"
  - "19:00"
  - "19:30"
  - "20:00"
  - "20:30"
  - "21:00"
  - "21:30"
  - "22:00"
  - "22:30"
  - "23:00"
  - "23:30"

valid_room_capacity:
  - "LessThan5Pax"
  - "From6To10Pax"
  - "From11To15Pax"
  - "From16To20Pax"
  - "From21To50Pax"
  - "From51To100Pax"
  - "MoreThan100Pax"

valid_buildings:
  - "Administration Building"
  - "Campus Open Spaces - Events/Activities"
  - "Concourse - Room/Lab"
  - "Lee Kong Chian School of Business"
  - "Li Ka Shing Library"
  - "Prinsep Street Residences"
  - "School of Accountancy"
  - "School of Computing & Information Systems 1"
  - "School of Economics/School of Computing & Information Systems 2"
  - "School of Social Sciences/College of Integrative Studies"
  - "SMU Connexion"
  - "Yong Pung How School of Law/Kwa Geok Choo Law Library"

valid_floors:
  - "Basement 0"
  - "Basement 2"
  - "Level 1"
  - "Level 2"
  - "Level 3"
  - "Level 4"
  - "Level 5"
  - "Level 6"
  - "Level 7"
  - "Level 8"
  - "Level 9"
  - "Level 10"
  - "Level 11"
  - "Level 12"
  - "Level 13"
  - "Level 14"

valid_facility_types:
  - "Chatterbox"
  - "Classroom"
  - "Group Study Room"
  - "Hostel Facilities"
  - "Meeting Pod"
  - "MPH / Sports Hall"
  - "Phone Booth"
  - "Project Room"
  - "Project Room (Level 5)"
  - "Seminar Room"
  - "SMUC Facilities"
  - "Student Activities Area"
  - "Study Booth"

valid_equipment:
  - "Classroom PC"
  - "Classroom Prompter"
  - "Clip-on Mic"
  - "Doc Camera"
  - "DVD Player"
  - "Gooseneck Mic"
  - "Handheld Mic"
  - "Hybrid (USB connection)"
  - "In-room VC System"
  - "Projector"
  - "Rostrum Mic"
  - "Teams Room"
  - "Teams Room NEAT Board"
  - "TV Panel"
  - "USB Connection VC room"
  - "Video Recording"
  - "Wired Mic"
  - "Wireless Projection"
